"use client"

import { useState, useRef, useEffect } from "react"
import { Loader2 } from "lucide-react"
import { GameBuilderLayout } from "./game-builder-layout"
import type { GameDesignDoc } from "@/lib/game-types"

// Per-template chip lists, generated by /api/templates and shipped
// inline with each template card. The template-chat is a state machine
// that walks the learner through 3 chip-driven steps + a confirm:
//
//   1. Theme    — what world / setting
//   2. Action   — what the player physically does on screen
//   3. Win      — how the player knows they won
//   4. Confirm  — review the assembled summary, then build
//
// No streaming, no AI calls during the steps — the chips are
// pre-generated. We only call the AI once at the end to extract a
// design doc from the captured answers.
export interface TemplateForChat {
  title: string
  description: string
  themeChips: string[]
  actionChips: string[]
  winChips: string[]
}

interface TemplateChatProps {
  template: TemplateForChat
  standardId: string
  standardDescription: string
  planetId: string
  onUnlock: () => void
  onBuildGame: (designDoc: GameDesignDoc, chatHistory: string) => void
}

type Step = "theme" | "action" | "win" | "confirm"

interface ChatTurn {
  role: "ai" | "user"
  text: string
}

// The 3 picks the learner makes via chips. Once all 3 are filled,
// we have everything needed to build the design doc.
interface Picks {
  theme: string | null
  action: string | null
  win: string | null
}

export function TemplateChat({
  template,
  standardId,
  standardDescription,
  planetId,
  onUnlock,
  onBuildGame,
}: TemplateChatProps) {
  const [step, setStep] = useState<Step>("theme")
  const [picks, setPicks] = useState<Picks>({ theme: null, action: null, win: null })
  const [customInput, setCustomInput] = useState("")
  const [history, setHistory] = useState<ChatTurn[]>([
    {
      role: "ai",
      text: `Got it — you picked ${template.title}. ${stripPeriod(template.description)}. The math is already covered, so we just need to fill in the details. First: what world should this happen in?`,
    },
  ])
  const [building, setBuilding] = useState(false)
  const scrollRef = useRef<HTMLDivElement>(null)

  // Auto-scroll to bottom when history changes
  useEffect(() => {
    scrollRef.current?.scrollTo({
      top: scrollRef.current.scrollHeight,
      behavior: "smooth",
    })
  }, [history, step])

  // Pick a chip OR submit a custom answer for the current step.
  // Records the pick, appends both turns to history, and advances.
  const handlePick = (value: string) => {
    if (!value.trim()) return
    const trimmed = value.trim()

    setHistory((prev) => [...prev, { role: "user", text: trimmed }])
    setCustomInput("")

    if (step === "theme") {
      setPicks((p) => ({ ...p, theme: trimmed }))
      setHistory((prev) => [
        ...prev,
        {
          role: "ai",
          text: `OK — ${trimmed}. Next: what does the player actually DO on the screen?`,
        },
      ])
      setStep("action")
      return
    }

    if (step === "action") {
      setPicks((p) => ({ ...p, action: trimmed }))
      setHistory((prev) => [
        ...prev,
        {
          role: "ai",
          text: `Got it — ${stripPeriod(trimmed).toLowerCase()}. Last question: how does the player know they won?`,
        },
      ])
      setStep("win")
      return
    }

    if (step === "win") {
      setPicks((p) => ({ ...p, win: trimmed }))
      // Advance to confirm step (no extra AI line — the summary card
      // below speaks for itself).
      setStep("confirm")
      return
    }
  }

  // When the learner hits the build button on the confirm screen,
  // assemble the picks into a chat-history-like blob, send it to the
  // existing /api/game/design-doc endpoint, and pass the result up
  // to the parent so the build screen can take over.
  const handleBuild = async () => {
    if (!picks.theme || !picks.action || !picks.win) return
    setBuilding(true)
    try {
      const summary = `Template: ${template.title}
Mechanic: ${template.description}
Theme / world: ${picks.theme}
Player action: ${picks.action}
Win condition: ${picks.win}`

      const res = await fetch("/api/game/design-doc", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          chatHistory: summary,
          standardId,
          standardDescription,
          planetId,
        }),
      })
      const designDoc = (await res.json()) as GameDesignDoc
      onBuildGame(designDoc, summary)
    } catch {
      // If the design-doc extraction fails, fall back to unlocking
      // the standard so the learner isn't stuck.
      onUnlock()
    } finally {
      setBuilding(false)
    }
  }

  // Pre-checked criteria for template mode: authentic + essential are
  // auto-met because the verb itself was verified by the templates
  // generator. Playable lights up only after the 3 picks are made
  // (since the picks together describe a fully playable game).
  const allPicked = !!picks.theme && !!picks.action && !!picks.win
  const criteria = {
    playable: allPicked,
    authentic: true,
    essential: true,
  }

  // The chip menu shown for the current step. Returns null on the
  // confirm step (no chips, just the summary card).
  const currentChips =
    step === "theme"
      ? template.themeChips
      : step === "action"
        ? template.actionChips
        : step === "win"
          ? template.winChips
          : null

  return (
    <GameBuilderLayout
      criteria={criteria}
      preChecked={["authentic", "essential"]}
      gameCard={{
        theme: picks.theme || undefined,
        action: picks.action || undefined,
        win: picks.win || undefined,
      }}
    >
      <div className="flex flex-col h-full">
        {/* Scrollable area: chat + chips together */}
        <div ref={scrollRef} className="flex-1 overflow-y-auto rounded-lg border border-zinc-800 p-3 min-h-0 space-y-3">
          <div className="flex items-center justify-between">
            <p className="text-sm text-zinc-300">
              {step === "confirm" ? "Ready to build" : `Step ${stepIndex(step)}/3`}
            </p>
          </div>

          {/* Chat history */}
          <div className="flex flex-col gap-2">
            {history.map((turn, i) => (
              <div
                key={i}
                className={`max-w-[85%] rounded-lg px-3 py-2 text-sm ${
                  turn.role === "user"
                    ? "self-end bg-zinc-800 text-zinc-100"
                    : "self-start bg-zinc-900 text-zinc-300"
                }`}
              >
                {turn.text}
              </div>
            ))}
          </div>

          {/* Chip menu (steps 1-3) — right below the last message */}
          {currentChips && (
            <div className="space-y-2 pt-1">
              <div className="flex flex-wrap gap-2">
                {currentChips.map((chip) => (
                  <button
                    key={chip}
                    onClick={() => handlePick(chip)}
                    className="bg-zinc-900 hover:bg-zinc-800 border border-zinc-700 hover:border-blue-500/50 text-zinc-200 text-xs font-medium rounded-full px-3 py-1.5 transition-colors"
                  >
                    {chip}
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Input — always visible at the bottom */}
        {currentChips && (
          <form
            onSubmit={(e) => {
              e.preventDefault()
              handlePick(customInput)
            }}
            className="flex gap-2 mt-2 shrink-0"
          >
            <input
              type="text"
              value={customInput}
              onChange={(e) => setCustomInput(e.target.value)}
              placeholder="Or type your own idea..."
              className="flex-1 rounded-lg border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-100 placeholder:text-zinc-500 focus:border-zinc-600 focus:outline-none"
            />
            <button
              type="submit"
              disabled={!customInput.trim()}
              className="rounded-lg bg-blue-600 hover:bg-blue-500 px-4 py-2 text-sm text-white font-medium disabled:opacity-30 transition-colors"
            >
              Send
            </button>
          </form>
        )}

        {/* Confirm step */}
        {step === "confirm" && (
          <div className="flex gap-2 mt-2 shrink-0">
            <button
              onClick={() => {
                setPicks({ theme: null, action: null, win: null })
                setStep("theme")
                setHistory([history[0]])
              }}
              className="flex-1 rounded-lg border border-zinc-700 bg-zinc-900 hover:bg-zinc-800 text-zinc-300 text-sm font-medium py-3 transition-colors"
            >
              Start over
            </button>
            <button
              onClick={handleBuild}
              disabled={building}
              className="flex-[2] rounded-lg bg-emerald-600 hover:bg-emerald-500 disabled:opacity-70 text-white text-sm font-semibold py-3 transition-colors"
            >
              {building ? (
                <span className="flex items-center justify-center gap-2">
                  <Loader2 className="size-4 animate-spin" />
                  Preparing...
                </span>
              ) : (
                "Build my game →"
              )}
            </button>
          </div>
        )}
      </div>
    </GameBuilderLayout>
  )
}

function stepIndex(step: Step): number {
  return step === "theme" ? 1 : step === "action" ? 2 : step === "win" ? 3 : 3
}

function stripPeriod(s: string): string {
  return s.replace(/[.!?]+$/, "")
}
