// Shared types for all pre-built game engines.

export interface ThemeConfig {
  title: string           // game title (learner-chosen)
  character: string       // who you play as
  itemName: string        // what you interact with (e.g. "cursed bricks", "gems")
  targetName: string      // what you're building/filling/matching (e.g. "tower", "potion")
  worldName: string       // the setting (e.g. "haunted castle")
  colors: {
    bg: string            // background color
    primary: string       // main interactive element color
    secondary: string     // secondary element color
    accent: string        // highlights, score, success
    danger: string        // wrong/failure color
    text: string          // text color
  }
  winMessage: string      // shown on victory
  loseMessage: string     // shown on defeat
  dare?: string           // optional dare from the learner
  // Sprite overrides (Phase 1: Phaser engines)
  characterSprite?: string   // sprite library ID or upload URL
  itemSprite?: string        // sprite library ID or upload URL
  backgroundImage?: string   // sprite library ID or upload URL
}

// What the AI generates from the circuit board builder choices
export interface ThemeConfigRequest {
  mechanic: string
  theme: string
  character: string
  action: string
  winCondition: string
  mathSkill: string
  title: string
  dare?: string
}

// Game option — each engine supports 3 genuinely different gameplay modes.
// Each option is a different way to play the same math, not just a difficulty tweak.
// Example: Balance & Equalize has "free-balance", "mystery-side", "chain-scales".
export type GameOption = string

// Deprecated alias — existing DOM engines still reference this.
// Will be removed once all engines are migrated to Phaser.
export type GameVariant = GameOption

// Each engine exports this function signature
export type GameEngine = (config: ThemeConfig, mathParams: MathParams, option?: GameOption) => string

// A single round of math content, generated by AI for the specific standard
export interface RoundData {
  prompt: string          // what the player sees, e.g. "3 + ? = 7" or "Find the area of a 4×3 rectangle"
  target: number          // the correct answer to collect
  items: number[]         // values shown on items (must include a valid subset summing to target)
  hint?: string           // optional hint shown in help panel
}

// Math parameters — what numbers/difficulty to use
export interface MathParams {
  grade: string           // K, 1, 2, ... 8, HS
  standardId: string      // e.g. "6.EE.B.7"
  standardDescription: string
  difficulty: "easy" | "medium" | "hard"
  rounds?: RoundData[]    // AI-generated rounds tailored to the specific standard
}

// Default color palette for all games
export const DEFAULT_PALETTE: ThemeConfig["colors"] = {
  bg: "#18181b",
  primary: "#60a5fa",
  secondary: "#e4e4e7",
  accent: "#fbbf24",
  danger: "#ef4444",
  text: "#e4e4e7",
}
